services:
  db:
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bitiya_db
      POSTGRES_USER: bitiya_user
      POSTGRES_PASSWORD: your_strong_password_here
    networks:
      - internal_network

  web:
    build: .
    restart: always
    # Порт 8000 на контейнере будет автоматически связан с портом 80 на сервере
    # Не нужно указывать "8000:8000", так как порты 80 и 443 зарезервированы [citation:6]
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://bitiya_user:your_strong_password_here@db:5432/bitiya_db
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  postgres_data: