services:
  db:
    image: postgres:17
    restart: always
    volumes:                               # <-- ЭТО НУЖНО, ЭТО ПРАВИЛЬНО
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bitiya_db
      POSTGRES_USER: bitiya_user
      POSTGRES_PASSWORD: Shalashino1720
    networks:
      - internal_network

  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://bitiya_user:Shalashino1720@db:5432/bitiya_db
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:                                  # <-- ЭТО НУЖНО, ЭТО ПРАВИЛЬНО
  postgres_data: