# Generated by Django 6.0.3 on 2026-05-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_gift_usergift'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gifts_count',
            field=models.IntegerField(default=0, verbose_name='Количество подарков'),
        ),
    ]
