# Generated by Django 6.0.3 on 2026-05-20 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_gifts_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новое уведомление')),
                ('viewed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to=settings.AUTH_USER_MODEL, verbose_name='Чей профиль')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to=settings.AUTH_USER_MODEL, verbose_name='Кто посмотрел')),
            ],
            options={
                'verbose_name': 'Просмотр профиля',
                'verbose_name_plural': 'Просмотры профилей',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
